### ISSUE TITLE
Extension host is crashing repeatedly

### ISSUE THREAD

**Issue by Zorono** [openmultiplayer/vscode-pawn#7]
It is confirmed that this extension is crashing my VSC's **Extensions host**

I just tried to open my **Pawn Language** dedicated workspace and found that the extension host is crashing repeatedly...

```
workbench.desktop.main.js:1925 Extension Host
workbench.desktop.main.js:1925 /home/johnm/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:123      throw ex;      ^RuntimeError: abort(Git error {  "exitCode": 128,  "stdout": "",  "stderr": ""}) at Error:     at jsStackTrace (/home/johnm/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1796:17)    at stackTrace (/home/johnm/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1813:16)    at process.abort (/home/johnm/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1596:44)    at process.emit (node:events:538:35)    at process.emit (/home/johnm/.vscode/extensions/node_modules/source-map-support/source-map-support.js:516:21)    at processEmit (/home/johnm/.vscode/extensions/node_modules/signal-exit/index.js:199:34)    at process.on.process.emit (/home/johnm/.vscode/extensions/zignd.html-css-class-completion-1.20.0/dist/extension.js:2:802330)    at processEmit [as emit] (/home/johnm/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.5823/extension.js:394:51519)    at emit (node:internal/process/promises:140:20)    at processPromiseRejections (node:internal/process/promises:274:27)    at processTicksAndRejections (node:internal/process/task_queues:97:32)    at process.abort (/home/johnm/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1602:9)    at process.emit (node:events:538:35)    at process.emit (/home/johnm/.vscode/extensions/node_modules/source-map-support/source-map-support.js:516:21)    at processEmit (/home/johnm/.vscode/extensions/node_modules/signal-exit/index.js:199:34)    at process.on.process.emit (/home/johnm/.vscode/extensions/zignd.html-css-class-completion-1.20.0/dist/extension.js:2:802330)    at processEmit [as emit] (/home/johnm/.vscode/extensions/ms-vsliveshare.vsliveshare-1.0.5823/extension.js:394:51519)    at emit (node:internal/process/promises:140:20)    at processPromiseRejections (node:internal/process/promises:274:27)    at processTicksAndRejections (node:internal/process/task_queues:97:32) {  vslsStack: [    CallSite {}, CallSite {},    CallSite {}, CallSite {},    CallSite {}, CallSite {},    CallSite {}, CallSite {},    CallSite {}  ]}
workbench.desktop.main.js:616   ERR A system error occurred (read ECONNRESET): Error: read ECONNRESET
    at __node_internal_captureLargerStackTrace (node:internal/errors:464:5)
    at __node_internal_errnoException (node:internal/errors:594:12)
    at Pipe.onStreamRead (node:internal/stream_base_commons:217:20)
workbench.desktop.main.js:2834 Extension host (LocalProcess) terminated unexpectedly. Code: 7, Signal: null
workbench.desktop.main.js:616   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
workbench.desktop.main.js:774 Extension host terminated unexpectedly 3 times within the last 5 minutes.
```

VS Code version: Code 1.74.3 (https://github.com/microsoft/vscode/commit/97dec172d3256f8ca4bfb2143f3f76b503ca0534, 2023-01-09T16:57:40.428Z)
Extension Version: 1.1.5

Related issue: https://github.com/microsoft/vscode/issues/172686

**Comment by Zorono** [comment]
![image](https://user-images.githubusercontent.com/19735243/232491713-5ab4d725-17c9-4ab6-9f3a-60c747cf5c06.png)
![image](https://user-images.githubusercontent.com/19735243/232546944-6a24b16c-5bd0-47a5-b3f2-22fc2de7577e.png)

**Comment by Zorono** [comment]
@AmyrAhmady 


> ![image](https://user-images.githubusercontent.com/19735243/232491713-5ab4d725-17c9-4ab6-9f3a-60c747cf5c06.png) ![image](https://user-images.githubusercontent.com/19735243/232546944-6a24b16c-5bd0-47a5-b3f2-22fc2de7577e.png)


in addition to, after disabling **wallabyjs.console-ninja** it showed a new error related to submodule **amx_assembly**'s **amx_base.inc**:
```
Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}
```

full log;
```
console.ts:137 [Extension Host] activate
console.ts:137 [Extension Host] Lua:MTA LUA: Init
console.ts:137 [Extension Host] MTA:SA LUA: Init
mainThreadExtensionService.ts:112 Activating extension 'subtixx.mtasa-lua' failed: command 'extension.mta-new-resource' already exists.
$onExtensionActivationError @ mainThreadExtensionService.ts:112
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] Looking for parseable documents...
console.ts:137 [Extension Host] Found no documents
console.ts:137 [Extension Host] Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}
console.ts:137 [Extension Host] Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
mainThreadExtensionService.ts:80 [[object Object]]abort(Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}) at Error: 
    at jsStackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1796:17)
    at stackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1813:16)
    at process.abort (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1596:44)
    at process.emit (node:events:538:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
mainThreadExtensionService.ts:81 RuntimeError: abort(Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}) at Error: 
    at jsStackTrace (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1796:17)
    at stackTrace (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1813:16)
    at process.abort (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1596:44)
    at process.emit (node:events:538:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
    at process.abort (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1602:9)
    at process.emit (node:events:538:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
abstractExtensionService.ts:604 Extension host (LocalProcess) terminated unexpectedly. Code: 7, Signal: unknown
mb @ abstractExtensionService.ts:604
mb @ nativeExtensionService.ts:165
lb @ abstractExtensionService.ts:596
(anonymous) @ abstractExtensionService.ts:574
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
M @ localProcessExtensionHost.ts:509
(anonymous) @ localProcessExtensionHost.ts:303
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
_ @ ipc.ts:672
t @ ipc.ts:740
s @ ipc.ts:729
(anonymous) @ ipc.ts:549
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
ee @ event.ts:457
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:81
log.ts:441   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
log.ts:421  INFO Automatically restarting the extension host.
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 /home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:123      throw ex;      ^RuntimeError: abort(Git error {  "exitCode": 128,  "gitErrorCode": "IsInSubmodule",  "stdout": "",  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"}) at Error:     at jsStackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1796:17)    at stackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1813:16)    at process.abort (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1596:44)    at process.emit (node:events:538:35)    at emit (node:internal/process/promises:140:20)    at processPromiseRejections (node:internal/process/promises:274:27)    at processTicksAndRejections (node:internal/process/task_queues:97:32)    at process.abort (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1602:9)    at process.emit (node:events:538:35)    at emit (node:internal/process/promises:140:20)    at processPromiseRejections (node:internal/process/promises:274:27)    at processTicksAndRejections (node:internal/process/task_queues:97:32)
console.ts:137 [Extension Host] activate
console.ts:137 [Extension Host] Lua:MTA LUA: Init
console.ts:137 [Extension Host] MTA:SA LUA: Init
mainThreadExtensionService.ts:112 Activating extension 'subtixx.mtasa-lua' failed: command 'extension.mta-new-resource' already exists.
$onExtensionActivationError @ mainThreadExtensionService.ts:112
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
console.ts:137 [Extension Host] Looking for parseable documents...
console.ts:137 [Extension Host] Found no documents
console.ts:137 [Extension Host] Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}
console.ts:137 [Extension Host] Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}
T @ console.ts:137
$logExtensionHostMessage @ mainThreadConsole.ts:39
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
mainThreadExtensionService.ts:80 [[object Object]]abort(Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}) at Error: 
    at jsStackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1796:17)
    at stackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1813:16)
    at process.abort (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1596:44)
    at process.emit (node:events:538:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:80
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
mainThreadExtensionService.ts:81 RuntimeError: abort(Git error {
  "exitCode": 128,
  "gitErrorCode": "IsInSubmodule",
  "stdout": "",
  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"
}) at Error: 
    at jsStackTrace (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1796:17)
    at stackTrace (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1813:16)
    at process.abort (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1596:44)
    at process.emit (node:events:538:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
    at process.abort (vscode-file://vscode-app/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1602:9)
    at process.emit (node:events:538:35)
    at emit (node:internal/process/promises:140:20)
    at processPromiseRejections (node:internal/process/promises:274:27)
    at processTicksAndRejections (node:internal/process/task_queues:97:32)
$onExtensionRuntimeError @ mainThreadExtensionService.ts:81
N @ rpcProtocol.ts:455
M @ rpcProtocol.ts:440
H @ rpcProtocol.ts:370
G @ rpcProtocol.ts:296
(anonymous) @ rpcProtocol.ts:161
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
fire @ ipc.net.ts:671
G.onmessage @ localProcessExtensionHost.ts:617
abstractExtensionService.ts:604 Extension host (LocalProcess) terminated unexpectedly. Code: 7, Signal: unknown
mb @ abstractExtensionService.ts:604
mb @ nativeExtensionService.ts:165
lb @ abstractExtensionService.ts:596
(anonymous) @ abstractExtensionService.ts:574
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
M @ localProcessExtensionHost.ts:509
(anonymous) @ localProcessExtensionHost.ts:303
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
_ @ ipc.ts:672
t @ ipc.ts:740
s @ ipc.ts:729
(anonymous) @ ipc.ts:549
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
ee @ event.ts:457
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:81
log.ts:441   ERR Extension host (LocalProcess) terminated unexpectedly. No extensions were activated.
notificationsAlerts.ts:42 Extension host terminated unexpectedly 3 times within the last 5 minutes.
c @ notificationsAlerts.ts:42
(anonymous) @ notificationsAlerts.ts:28
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
addNotification @ notifications.ts:204
notify @ notificationService.ts:175
prompt @ notificationService.ts:253
mb @ nativeExtensionService.ts:230
lb @ abstractExtensionService.ts:596
(anonymous) @ abstractExtensionService.ts:574
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
M @ localProcessExtensionHost.ts:509
(anonymous) @ localProcessExtensionHost.ts:303
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
_ @ ipc.ts:672
t @ ipc.ts:740
s @ ipc.ts:729
(anonymous) @ ipc.ts:549
invoke @ event.ts:723
deliver @ event.ts:936
fire @ event.ts:892
ee @ event.ts:457
emit @ node:events:526
onMessage @ node:electron/js2c/renderer_init:81
localProcessExtensionHost.ts:293 Extension Host
localProcessExtensionHost.ts:294 /home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:123      throw ex;      ^RuntimeError: abort(Git error {  "exitCode": 128,  "gitErrorCode": "IsInSubmodule",  "stdout": "",  "stderr": "fatal: Pathspec '/sdc1/path/to/SA-MP Server/dependencies/amx_assembly/amx_base.inc' is in submodule 'dependencies/amx_assembly'\n"}) at Error:     at jsStackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1796:17)    at stackTrace (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1813:16)    at process.abort (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1596:44)    at process.emit (node:events:538:35)    at emit (node:internal/process/promises:140:20)    at processPromiseRejections (node:internal/process/promises:274:27)    at processTicksAndRejections (node:internal/process/task_queues:97:32)    at process.abort (/home/zorono/.vscode/extensions/openmp.pawn-development-1.1.5/node_modules/astyle/dist/libastyle.js:1602:9)    at process.emit (node:events:538:35)    at emit (node:internal/process/promises:140:20)    at processPromiseRejections (node:internal/process/promises:274:27)    at processTicksAndRejections (node:internal/process/task_queues:97:32)

```

**Comment by Zorono** [comment]
```
Version: 1.77.3
Commit: 704ed70d4fd1c6bd6342c436f1ede30d1cff4710
Date: 2023-04-12T09:16:52.732Z
Electron: 19.1.11
Chromium: 102.0.5005.196
Node.js: 16.14.2
V8: 10.2.154.26-electron.0
OS: Linux x64 5.19.0-38-generic
Sandboxed: No
```

**Comment by Zorono** [comment]
![image](https://user-images.githubusercontent.com/19735243/232959560-3e6d9886-5a1a-4a9a-bcb0-0d0676871312.png)
